name: UI tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  repository_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install Google Chrome
      run: sudo apt-get install google-chrome-stable

    - name: Run tests
      env:
        BASE_URL: https://twitch.tv/
        BROWSER: Mobile_Emulator
        SCREENSHOTS: ./resources/screenshots/
        TEST_LOG_DIR_PATH: ./resources/logs/
        TEST_LOG_LEVEL: INFO
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv run pytest ./tests/

    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: ./pytest-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
        title: Test results

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: ./resources/screenshots/
